/* Net simples_without_net - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include "net_types.h"


int trace_control = TRACE_CONT_RUN;

extern void httpServer_init();
extern void httpServer_getRequest();
extern void httpServer_sendResponse();
extern void httpServer_disconnectClient();
extern void httpServer_checkBreakPoints();
extern void httpServer_finish();

static simples_without_net_NetMarking marking;
static simples_without_net_InputSignals inputs, prev_inputs;
static simples_without_net_PlaceOutputSignals place_out;
static simples_without_net_EventOutputSignals ev_out;

void setup()
{
    createInitial_simples_without_net_NetMarking( &marking );
    init_simples_without_net_OutputSignals( &place_out, &ev_out );
    simples_without_net_InitializeIO();
    simples_without_net_GetInputSignals( &prev_inputs, NULL );
#ifdef HTTP_SERVER
    httpServer_init();
#endif
}

void loop()
{
#ifdef HTTP_SERVER
    httpServer_getRequest();
#endif

    if( trace_control != TRACE_PAUSE )
        simples_without_net_ExecutionStep( &marking, &inputs, &prev_inputs, &place_out, &ev_out );
    else simples_without_net_GetInputSignals( &inputs, NULL );
    if( trace_control > TRACE_PAUSE ) --trace_control;

#ifdef HTTP_SERVER
    httpServer_sendResponse();
#endif

    simples_without_net_LoopDelay();

#ifdef HTTP_SERVER
    httpServer_disconnectClient();
    httpServer_checkBreakPoints();
#endif
}

#ifndef ARDUINO
int main()
{
    setup();

    do loop();
    while( simples_without_net_FinishExecution( &marking ) == 0 );

#ifdef HTTP_SERVER
    httpServer_finish();
#endif

    return 0;
}
#endif


simples_without_net_NetMarking* get_simples_without_net_NetMarking()
{
    return &marking;
}

simples_without_net_InputSignals* get_simples_without_net_InputSignals()
{
    return &inputs;
}

simples_without_net_PlaceOutputSignals* get_simples_without_net_PlaceOutputSignals()
{
    return &place_out;
}

simples_without_net_EventOutputSignals* get_simples_without_net_EventOutputSignals()
{
    return &ev_out;
}

