/* Net N_3carros_TD - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include "net_types.h"


#define ABS(x) (((x)>=0)?(x):-(x))


/* Array implementation: */


void createInitial_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* init_marking )
{
    memset( init_marking, 0, sizeof(*init_marking) );
    init_marking->p_42 = 0; /* Place Car6_Move_Back */
    init_marking->p_43 = 0; /* Place Car6_Arrived */
    init_marking->p_44 = 0; /* Place Car_Move_Forward */
    init_marking->p_48 = 1; /* Place Car6_Ready */
}

void createEmpty_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* empty_marking )
{
    empty_marking->p_42 = 0; /* Place Car6_Move_Back */
    empty_marking->p_43 = 0; /* Place Car6_Arrived */
    empty_marking->p_44 = 0; /* Place Car_Move_Forward */
    empty_marking->p_48 = 0; /* Place Car6_Ready */
}

void add_N_3carros_TD_NetMarkings(
    N_3carros_TD_NetMarking* dest_marking,
    N_3carros_TD_NetMarking* source_marking )
{
    dest_marking->p_42 += source_marking->p_42; /* Place Car6_Move_Back */
    dest_marking->p_43 += source_marking->p_43; /* Place Car6_Arrived */
    dest_marking->p_44 += source_marking->p_44; /* Place Car_Move_Forward */
    dest_marking->p_48 += source_marking->p_48; /* Place Car6_Ready */
}

void init_N_3carros_TD_OutputSignals(
    N_3carros_TD_PlaceOutputSignals* place_out,
    N_3carros_TD_EventOutputSignals* ev_out )
{
    memset( place_out, 0, sizeof(*place_out) );
    memset( ev_out, 0, sizeof(*ev_out) );
    place_out->Car6_ready = 0;
    place_out->Car6_arrived = 0;
}

/* Transition 45 - BACK_copy6 */
int t_45_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_43 >= 1 );
}

int t_45_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event73 );
}

int t_45_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_45_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_43--;
}

void t_45_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_42++;
}

void t_45_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 46 - B6 */
int t_46_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_44 >= 1 );
}

int t_46_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_46_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_46_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_44--;
}

void t_46_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_43++;
}

void t_46_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
    ev_out->event72 = 1;
}


/* Transition 47 - GO_copy6 */
int t_47_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_48 >= 1 );
}

int t_47_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event71 );
}

int t_47_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_47_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_48--;
}

void t_47_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_44++;
}

void t_47_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 49 - A6 */
int t_49_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_42 >= 1 );
}

int t_49_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_49_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_49_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_42--;
}

void t_49_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_48++;
}

void t_49_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
    ev_out->event70 = 1;
}


/* Input event processing: */
void N_3carros_TD_GenerateInputSignalEvents(
        N_3carros_TD_InputSignals *old_values,
        N_3carros_TD_InputSignals *new_values,
        N_3carros_TD_InputSignalEvents *events )
{
}

/* Output event processing: */
void N_3carros_TD_GenerateEventOutputSignals(
    N_3carros_TD_OutputSignalEvents *events,
    N_3carros_TD_EventOutputSignals *signals )
{
}

/* Transition action processing: */
void N_3carros_TD_GenerateTransitionActionOutputSignals(
    N_3carros_TD_TransitionFiring *tfired,
    N_3carros_TD_NetMarking *marking,
    N_3carros_TD_EventOutputSignals *ev_out )
{
}

/* Place Output Processing */
void N_3carros_TD_GeneratePlaceOutputSignals(
    N_3carros_TD_NetMarking *marking,
    N_3carros_TD_InputSignals *inputs,
    N_3carros_TD_PlaceOutputSignals *place_out,
    N_3carros_TD_EventOutputSignals *ev_out )
{
    int exp_res, new_val, n_writes;
    N_3carros_TD_PlaceOutputSignals new_out = *place_out;
    
    /* Signal Car6_ready */
    new_val = 0;
    if( marking->p_48 > 0 ) { /* Place Car6_Ready */
        exp_res = marking->p_48 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Car6_ready = 1;
    else if( new_val < 0 ) new_out.Car6_ready = 0;
    else new_out.Car6_ready = new_val;

    /* Signal Car6_arrived */
    new_val = 0;
    if( marking->p_43 > 0 ) { /* Place Car6_Arrived */
        exp_res = marking->p_43 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Car6_arrived = 1;
    else if( new_val < 0 ) new_out.Car6_arrived = 0;
    else new_out.Car6_arrived = new_val;

    *place_out = new_out;
}

