/* Net N_3carros_TD - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#ifndef __N_3carros_TD_DEFS
#define __N_3carros_TD_DEFS


#define TRACE_CONT_RUN       (-1)
#define TRACE_PAUSE          0
#define TRACE_SINGLE_STEP    1
#define TRACE_N_STEPS(n)     (n)

#define MODEL_NAME		N_3carros_TD
#define MODEL_NAME_STR		"N_3carros_TD"
#define MODEL_VERSION		"2017-05-09 21:43:32"
#define MODEL_N_INPUTS		0
#define MODEL_N_OUTPUTS		2
#define MODEL_N_PLACES		4
#define MODEL_N_TRANSITIONS	4

#ifdef __cplusplus
extern "C" {
#endif

extern int trace_control;

typedef struct {
    unsigned int p_90: 1; /* Place Car5_Move_Back */
    unsigned int p_91: 1; /* Place Car5_Arrived */
    unsigned int p_92: 1; /* Place Car5_Move_Forward */
    unsigned int p_96: 1; /* Place Car5_Ready */
    unsigned int padding: 4;
} N_3carros_TD_NetMarking;


typedef struct {
} N_3carros_TD_InputSignals;


typedef struct {
    unsigned int event114 : 1;
    unsigned int event115 : 1;
} N_3carros_TD_InputSignalEvents;


typedef struct {
    unsigned int event116 : 1;
    unsigned int event117 : 1;
    unsigned int padding : 6;
} N_3carros_TD_OutputSignalEvents;


typedef struct {
    unsigned int Car5_ready : 1;
    unsigned int Car5_arrived : 1;
} N_3carros_TD_PlaceOutputSignals;


typedef struct {
} N_3carros_TD_EventOutputSignals;


typedef struct {
    unsigned int t_93 : 1; /* BACK_copy5 */
    unsigned int t_94 : 1; /* B5 */
    unsigned int t_95 : 1; /* GO_copy5 */
    unsigned int t_97 : 1; /* A5 */
    unsigned int count: 8;
} N_3carros_TD_TransitionFiring;

/* Array declarations: */


/* Runtime text info: */
typedef struct {
#ifdef __cplusplus
    const
#endif
    char* name;
    int value;
} iopt_param_info;

extern iopt_param_info* get_N_3carros_TD_InputInfo();
extern iopt_param_info* get_N_3carros_TD_OutputInfo();
extern iopt_param_info* get_N_3carros_TD_MarkingInfo();
extern iopt_param_info* get_N_3carros_TD_TFiredInfo();
extern void force_N_3carros_TD_Inputs( iopt_param_info fv[], N_3carros_TD_InputSignals* in );
extern void force_N_3carros_TD_Outputs( iopt_param_info fv[], N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void force_N_3carros_TD_Marking( iopt_param_info fv[], N_3carros_TD_NetMarking* m );


extern void createInitial_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* init_marking );
extern void createEmpty_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* empty_marking );
extern void add_N_3carros_TD_NetMarkings( N_3carros_TD_NetMarking* dest_marking, N_3carros_TD_NetMarking* source_marking );

extern void init_N_3carros_TD_OutputSignals( N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );

/* Transition 93 - BACK_copy5 */
extern int  t_93_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_93_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_93_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_93_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_93_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_93_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 94 - B5 */
extern int  t_94_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_94_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_94_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_94_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_94_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_94_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 95 - GO_copy5 */
extern int  t_95_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_95_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_95_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_95_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_95_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_95_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 97 - A5 */
extern int  t_97_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_97_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_97_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_97_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_97_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_97_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
extern void N_3carros_TD_GenerateInputSignalEvents( N_3carros_TD_InputSignals *old_values, N_3carros_TD_InputSignals *new_values, N_3carros_TD_InputSignalEvents *events );

extern void N_3carros_TD_GenerateEventOutputSignals( N_3carros_TD_OutputSignalEvents *events, N_3carros_TD_EventOutputSignals *signals );

extern void N_3carros_TD_GenerateTransitionActionOutputSignals( N_3carros_TD_TransitionFiring *tfired, N_3carros_TD_NetMarking *marking, N_3carros_TD_EventOutputSignals *signals );

extern void N_3carros_TD_GeneratePlaceOutputSignals( N_3carros_TD_NetMarking *marking, N_3carros_TD_InputSignals *inputs, N_3carros_TD_PlaceOutputSignals *place_out, N_3carros_TD_EventOutputSignals *ev_out );

extern void N_3carros_TD_ExecutionStep( N_3carros_TD_NetMarking *prev_marking, N_3carros_TD_InputSignals *inputs, N_3carros_TD_InputSignals *prev_in, N_3carros_TD_PlaceOutputSignals *place_out, N_3carros_TD_EventOutputSignals *ev_out );

extern void N_3carros_TD_InitializeIO();
extern void N_3carros_TD_GetInputSignals( N_3carros_TD_InputSignals* inputs, N_3carros_TD_InputSignalEvents* events );
extern void N_3carros_TD_PutOutputSignals( N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* event_out, N_3carros_TD_OutputSignalEvents* events );
extern void N_3carros_TD_LoopDelay();
extern int N_3carros_TD_FinishExecution( N_3carros_TD_NetMarking* marking );

extern N_3carros_TD_NetMarking* get_N_3carros_TD_NetMarking();
extern N_3carros_TD_InputSignals* get_N_3carros_TD_InputSignals();
extern N_3carros_TD_PlaceOutputSignals* get_N_3carros_TD_PlaceOutputSignals();
extern N_3carros_TD_EventOutputSignals* get_N_3carros_TD_EventOutputSignals();
extern N_3carros_TD_TransitionFiring* get_N_3carros_TD_TransitionFiring();

#ifdef __cplusplus
};
#endif


#endif
