/* Net simples_without_net - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include <string.h>
#include "net_types.h"


static simples_without_net_TransitionFiring tfired;
    

void simples_without_net_ExecutionStep(
     simples_without_net_NetMarking *prev_marking,
     simples_without_net_InputSignals *inputs,
     simples_without_net_InputSignals *prev_in,
     simples_without_net_PlaceOutputSignals *place_out,
     simples_without_net_EventOutputSignals *ev_out )
{
    simples_without_net_NetMarking add_marking;
    simples_without_net_NetMarking avail_marking = *prev_marking;
    simples_without_net_InputSignalEvents input_events;
    simples_without_net_OutputSignalEvents output_events;

    memset( &output_events, 0, sizeof(output_events) );
    memset( &tfired, 0, sizeof(tfired) );

    createEmpty_simples_without_net_NetMarking( &add_marking );
    simples_without_net_GetInputSignals( inputs, &input_events );
    simples_without_net_GenerateInputSignalEvents( prev_in, inputs, &input_events );
    *prev_in = *inputs;

    /* Transition tr_8 */
    if( t_8_enabled( prev_marking, &avail_marking ) &&
        t_8_events( &input_events ) &&
        t_8_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_8 = 1;
        t_8_remove_marks( &avail_marking );
        t_8_add_marks( &add_marking );
        t_8_generate_output_events( &output_events );
    }

    /* Transition tr_10 */
    if( t_10_enabled( prev_marking, &avail_marking ) &&
        t_10_events( &input_events ) &&
        t_10_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_10 = 1;
        t_10_remove_marks( &avail_marking );
        t_10_add_marks( &add_marking );
        t_10_generate_output_events( &output_events );
    }

    add_simples_without_net_NetMarkings( &avail_marking, &add_marking );

    simples_without_net_GenerateTransitionActionOutputSignals( &tfired, &avail_marking, ev_out );
    simples_without_net_GeneratePlaceOutputSignals( &avail_marking, inputs, place_out, ev_out );
    simples_without_net_GenerateEventOutputSignals( &output_events, ev_out );
    simples_without_net_PutOutputSignals( place_out, ev_out, &output_events );
    *prev_marking = avail_marking;
}

simples_without_net_TransitionFiring* get_simples_without_net_TransitionFiring()
{
    return &tfired;
}

