/* Net N_3carros_TD - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#ifndef __N_3carros_TD_DEFS
#define __N_3carros_TD_DEFS


#define TRACE_CONT_RUN       (-1)
#define TRACE_PAUSE          0
#define TRACE_SINGLE_STEP    1
#define TRACE_N_STEPS(n)     (n)

#define MODEL_NAME		N_3carros_TD
#define MODEL_NAME_STR		"N_3carros_TD"
#define MODEL_VERSION		"2017-05-09 21:39:26"
#define MODEL_N_INPUTS		0
#define MODEL_N_OUTPUTS		6
#define MODEL_N_PLACES		20
#define MODEL_N_TRANSITIONS	20

#ifdef __cplusplus
extern "C" {
#endif

extern int trace_control;

typedef struct {
    unsigned int p_2: 1; /* Place Car1_Move_Back */
    unsigned int p_3: 1; /* Place Car1_Ready */
    unsigned int p_4: 1; /* Place Car1_Arrived */
    unsigned int p_5: 1; /* Place Car2_Arrived_copy */
    unsigned int p_6: 1; /* Place Car1_Move_Forward */
    unsigned int p_12: 1; /* Place Car2_Ready_copy */
    unsigned int p_14: 1; /* Place Car3_Ready_copy */
    unsigned int p_16: 1; /* Place Car3_Arrived_copy */
    unsigned int p_78: 1; /* Place Car4_Ready_copy */
    unsigned int p_80: 1; /* Place Car6_Ready_copy */
    unsigned int p_82: 1; /* Place Car8_Ready_copy */
    unsigned int p_84: 1; /* Place Car4_Arrived_copy */
    unsigned int p_86: 1; /* Place Car6_Arrived_copy */
    unsigned int p_88: 1; /* Place Car8_Arrived_copy */
    unsigned int p_126: 1; /* Place Car5_Ready_copy */
    unsigned int p_128: 1; /* Place Car7_Ready_copy */
    unsigned int p_130: 1; /* Place Car9_Ready_copy */
    unsigned int p_132: 1; /* Place Car5_Arrived_copy */
    unsigned int p_134: 1; /* Place Car7_Arrived_copy */
    unsigned int p_136: 1; /* Place Car9_Arrived_copy */
    unsigned int padding: 4;
} N_3carros_TD_NetMarking;


typedef struct {
} N_3carros_TD_InputSignals;


typedef struct {
    unsigned int event70 : 1;
    unsigned int event72 : 1;
    unsigned int event116 : 1;
    unsigned int event117 : 1;
} N_3carros_TD_InputSignalEvents;


typedef struct {
    unsigned int event71 : 1;
    unsigned int event73 : 1;
    unsigned int event114 : 1;
    unsigned int event115 : 1;
    unsigned int padding : 4;
} N_3carros_TD_OutputSignalEvents;


typedef struct {
    unsigned int car1_ready : 1;
    unsigned int car1_arrived : 1;
    unsigned int car5_ready : 1;
    unsigned int car5_arrived : 1;
    unsigned int car6_ready : 1;
    unsigned int car6_arrived : 1;
} N_3carros_TD_PlaceOutputSignals;


typedef struct {
} N_3carros_TD_EventOutputSignals;


typedef struct {
    unsigned int t_7 : 1; /* A1 */
    unsigned int t_8 : 1; /* GO */
    unsigned int t_9 : 1; /* BACK */
    unsigned int t_10 : 1; /* B1 */
    unsigned int t_11 : 1; /* B2_copy */
    unsigned int t_13 : 1; /* A2_copy */
    unsigned int t_15 : 1; /* A3_copy */
    unsigned int t_17 : 1; /* B3_copy */
    unsigned int t_79 : 1; /* A4_copy */
    unsigned int t_81 : 1; /* A6_copy */
    unsigned int t_83 : 1; /* A8_copy */
    unsigned int t_85 : 1; /* B4_copy */
    unsigned int t_87 : 1; /* B6_copy */
    unsigned int t_89 : 1; /* B8_copy */
    unsigned int t_127 : 1; /* A5_copy */
    unsigned int t_129 : 1; /* A7_copy */
    unsigned int t_131 : 1; /* A9_copy */
    unsigned int t_133 : 1; /* B5_copy */
    unsigned int t_135 : 1; /* B7_copy */
    unsigned int t_137 : 1; /* B9_copy */
    unsigned int count: 8;
} N_3carros_TD_TransitionFiring;

/* Array declarations: */


/* Runtime text info: */
typedef struct {
#ifdef __cplusplus
    const
#endif
    char* name;
    int value;
} iopt_param_info;

extern iopt_param_info* get_N_3carros_TD_InputInfo();
extern iopt_param_info* get_N_3carros_TD_OutputInfo();
extern iopt_param_info* get_N_3carros_TD_MarkingInfo();
extern iopt_param_info* get_N_3carros_TD_TFiredInfo();
extern void force_N_3carros_TD_Inputs( iopt_param_info fv[], N_3carros_TD_InputSignals* in );
extern void force_N_3carros_TD_Outputs( iopt_param_info fv[], N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void force_N_3carros_TD_Marking( iopt_param_info fv[], N_3carros_TD_NetMarking* m );


extern void createInitial_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* init_marking );
extern void createEmpty_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* empty_marking );
extern void add_N_3carros_TD_NetMarkings( N_3carros_TD_NetMarking* dest_marking, N_3carros_TD_NetMarking* source_marking );

extern void init_N_3carros_TD_OutputSignals( N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );

/* Transition 7 - A1 */
extern int  t_7_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_7_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_7_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_7_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_7_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_7_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 8 - GO */
extern int  t_8_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_8_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_8_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_8_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_8_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_8_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 9 - BACK */
extern int  t_9_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_9_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_9_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_9_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_9_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_9_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 10 - B1 */
extern int  t_10_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_10_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_10_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_10_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_10_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_10_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 11 - B2_copy */
extern int  t_11_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_11_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_11_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_11_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_11_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_11_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 13 - A2_copy */
extern int  t_13_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_13_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_13_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_13_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_13_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_13_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 15 - A3_copy */
extern int  t_15_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_15_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_15_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_15_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_15_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_15_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 17 - B3_copy */
extern int  t_17_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_17_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_17_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_17_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_17_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_17_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 79 - A4_copy */
extern int  t_79_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_79_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_79_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_79_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_79_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_79_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 81 - A6_copy */
extern int  t_81_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_81_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_81_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_81_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_81_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_81_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 83 - A8_copy */
extern int  t_83_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_83_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_83_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_83_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_83_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_83_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 85 - B4_copy */
extern int  t_85_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_85_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_85_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_85_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_85_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_85_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 87 - B6_copy */
extern int  t_87_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_87_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_87_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_87_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_87_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_87_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 89 - B8_copy */
extern int  t_89_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_89_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_89_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_89_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_89_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_89_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 127 - A5_copy */
extern int  t_127_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_127_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_127_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_127_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_127_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_127_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 129 - A7_copy */
extern int  t_129_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_129_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_129_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_129_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_129_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_129_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 131 - A9_copy */
extern int  t_131_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_131_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_131_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_131_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_131_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_131_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 133 - B5_copy */
extern int  t_133_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_133_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_133_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_133_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_133_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_133_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 135 - B7_copy */
extern int  t_135_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_135_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_135_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_135_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_135_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_135_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
/* Transition 137 - B9_copy */
extern int  t_137_enabled( N_3carros_TD_NetMarking* prev, N_3carros_TD_NetMarking* avail );
extern int  t_137_events( N_3carros_TD_InputSignalEvents* events );
extern int  t_137_guards( N_3carros_TD_NetMarking* marking, N_3carros_TD_InputSignals* inputs, N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* ev_out );
extern void t_137_remove_marks( N_3carros_TD_NetMarking* marking );
extern void t_137_add_marks( N_3carros_TD_NetMarking* marking );
extern void t_137_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out );
extern void N_3carros_TD_GenerateInputSignalEvents( N_3carros_TD_InputSignals *old_values, N_3carros_TD_InputSignals *new_values, N_3carros_TD_InputSignalEvents *events );

extern void N_3carros_TD_GenerateEventOutputSignals( N_3carros_TD_OutputSignalEvents *events, N_3carros_TD_EventOutputSignals *signals );

extern void N_3carros_TD_GenerateTransitionActionOutputSignals( N_3carros_TD_TransitionFiring *tfired, N_3carros_TD_NetMarking *marking, N_3carros_TD_EventOutputSignals *signals );

extern void N_3carros_TD_GeneratePlaceOutputSignals( N_3carros_TD_NetMarking *marking, N_3carros_TD_InputSignals *inputs, N_3carros_TD_PlaceOutputSignals *place_out, N_3carros_TD_EventOutputSignals *ev_out );

extern void N_3carros_TD_ExecutionStep( N_3carros_TD_NetMarking *prev_marking, N_3carros_TD_InputSignals *inputs, N_3carros_TD_InputSignals *prev_in, N_3carros_TD_PlaceOutputSignals *place_out, N_3carros_TD_EventOutputSignals *ev_out );

extern void N_3carros_TD_InitializeIO();
extern void N_3carros_TD_GetInputSignals( N_3carros_TD_InputSignals* inputs, N_3carros_TD_InputSignalEvents* events );
extern void N_3carros_TD_PutOutputSignals( N_3carros_TD_PlaceOutputSignals* place_out, N_3carros_TD_EventOutputSignals* event_out, N_3carros_TD_OutputSignalEvents* events );
extern void N_3carros_TD_LoopDelay();
extern int N_3carros_TD_FinishExecution( N_3carros_TD_NetMarking* marking );

extern N_3carros_TD_NetMarking* get_N_3carros_TD_NetMarking();
extern N_3carros_TD_InputSignals* get_N_3carros_TD_InputSignals();
extern N_3carros_TD_PlaceOutputSignals* get_N_3carros_TD_PlaceOutputSignals();
extern N_3carros_TD_EventOutputSignals* get_N_3carros_TD_EventOutputSignals();
extern N_3carros_TD_TransitionFiring* get_N_3carros_TD_TransitionFiring();

#ifdef __cplusplus
};
#endif


#endif
