/* Net N_3carros_TD - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include "net_types.h"


#define ABS(x) (((x)>=0)?(x):-(x))


/* Array implementation: */


void createInitial_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* init_marking )
{
    memset( init_marking, 0, sizeof(*init_marking) );
    init_marking->p_90 = 0; /* Place Car5_Move_Back */
    init_marking->p_91 = 0; /* Place Car5_Arrived */
    init_marking->p_92 = 0; /* Place Car5_Move_Forward */
    init_marking->p_96 = 1; /* Place Car5_Ready */
}

void createEmpty_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* empty_marking )
{
    empty_marking->p_90 = 0; /* Place Car5_Move_Back */
    empty_marking->p_91 = 0; /* Place Car5_Arrived */
    empty_marking->p_92 = 0; /* Place Car5_Move_Forward */
    empty_marking->p_96 = 0; /* Place Car5_Ready */
}

void add_N_3carros_TD_NetMarkings(
    N_3carros_TD_NetMarking* dest_marking,
    N_3carros_TD_NetMarking* source_marking )
{
    dest_marking->p_90 += source_marking->p_90; /* Place Car5_Move_Back */
    dest_marking->p_91 += source_marking->p_91; /* Place Car5_Arrived */
    dest_marking->p_92 += source_marking->p_92; /* Place Car5_Move_Forward */
    dest_marking->p_96 += source_marking->p_96; /* Place Car5_Ready */
}

void init_N_3carros_TD_OutputSignals(
    N_3carros_TD_PlaceOutputSignals* place_out,
    N_3carros_TD_EventOutputSignals* ev_out )
{
    memset( place_out, 0, sizeof(*place_out) );
    memset( ev_out, 0, sizeof(*ev_out) );
    place_out->Car5_ready = 0;
    place_out->Car5_arrived = 0;
}

/* Transition 93 - BACK_copy5 */
int t_93_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_91 >= 1 );
}

int t_93_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event114 );
}

int t_93_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_93_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_91--;
}

void t_93_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_90++;
}

void t_93_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 94 - B5 */
int t_94_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_92 >= 1 );
}

int t_94_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_94_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_94_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_92--;
}

void t_94_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_91++;
}

void t_94_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
    ev_out->event116 = 1;
}


/* Transition 95 - GO_copy5 */
int t_95_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_96 >= 1 );
}

int t_95_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event115 );
}

int t_95_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_95_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_96--;
}

void t_95_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_92++;
}

void t_95_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 97 - A5 */
int t_97_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_90 >= 1 );
}

int t_97_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_97_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_97_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_90--;
}

void t_97_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_96++;
}

void t_97_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
    ev_out->event117 = 1;
}


/* Input event processing: */
void N_3carros_TD_GenerateInputSignalEvents(
        N_3carros_TD_InputSignals *old_values,
        N_3carros_TD_InputSignals *new_values,
        N_3carros_TD_InputSignalEvents *events )
{
}

/* Output event processing: */
void N_3carros_TD_GenerateEventOutputSignals(
    N_3carros_TD_OutputSignalEvents *events,
    N_3carros_TD_EventOutputSignals *signals )
{
}

/* Transition action processing: */
void N_3carros_TD_GenerateTransitionActionOutputSignals(
    N_3carros_TD_TransitionFiring *tfired,
    N_3carros_TD_NetMarking *marking,
    N_3carros_TD_EventOutputSignals *ev_out )
{
}

/* Place Output Processing */
void N_3carros_TD_GeneratePlaceOutputSignals(
    N_3carros_TD_NetMarking *marking,
    N_3carros_TD_InputSignals *inputs,
    N_3carros_TD_PlaceOutputSignals *place_out,
    N_3carros_TD_EventOutputSignals *ev_out )
{
    int exp_res, new_val, n_writes;
    N_3carros_TD_PlaceOutputSignals new_out = *place_out;
    
    /* Signal Car5_ready */
    new_val = 0;
    if( marking->p_96 > 0 ) { /* Place Car5_Ready */
        exp_res = marking->p_96 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Car5_ready = 1;
    else if( new_val < 0 ) new_out.Car5_ready = 0;
    else new_out.Car5_ready = new_val;

    /* Signal Car5_arrived */
    new_val = 0;
    if( marking->p_91 > 0 ) { /* Place Car5_Arrived */
        exp_res = marking->p_91 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Car5_arrived = 1;
    else if( new_val < 0 ) new_out.Car5_arrived = 0;
    else new_out.Car5_arrived = new_val;

    *place_out = new_out;
}

