/* Net N_3carros_TD - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include <string.h>
#include "net_types.h"


static N_3carros_TD_TransitionFiring tfired;
    

void N_3carros_TD_ExecutionStep(
     N_3carros_TD_NetMarking *prev_marking,
     N_3carros_TD_InputSignals *inputs,
     N_3carros_TD_InputSignals *prev_in,
     N_3carros_TD_PlaceOutputSignals *place_out,
     N_3carros_TD_EventOutputSignals *ev_out )
{
    N_3carros_TD_NetMarking add_marking;
    N_3carros_TD_NetMarking avail_marking = *prev_marking;
    N_3carros_TD_InputSignalEvents input_events;
    N_3carros_TD_OutputSignalEvents output_events;

    memset( &output_events, 0, sizeof(output_events) );
    memset( &tfired, 0, sizeof(tfired) );

    createEmpty_N_3carros_TD_NetMarking( &add_marking );
    N_3carros_TD_GetInputSignals( inputs, &input_events );
    N_3carros_TD_GenerateInputSignalEvents( prev_in, inputs, &input_events );
    *prev_in = *inputs;

    /* Transition A1 */
    if( t_7_enabled( prev_marking, &avail_marking ) &&
        t_7_events( &input_events ) &&
        t_7_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_7 = 1;
        t_7_remove_marks( &avail_marking );
        t_7_add_marks( &add_marking );
        t_7_generate_output_events( &output_events );
    }

    /* Transition GO */
    if( t_8_enabled( prev_marking, &avail_marking ) &&
        t_8_events( &input_events ) &&
        t_8_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_8 = 1;
        t_8_remove_marks( &avail_marking );
        t_8_add_marks( &add_marking );
        t_8_generate_output_events( &output_events );
    }

    /* Transition BACK */
    if( t_9_enabled( prev_marking, &avail_marking ) &&
        t_9_events( &input_events ) &&
        t_9_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_9 = 1;
        t_9_remove_marks( &avail_marking );
        t_9_add_marks( &add_marking );
        t_9_generate_output_events( &output_events );
    }

    /* Transition B1 */
    if( t_10_enabled( prev_marking, &avail_marking ) &&
        t_10_events( &input_events ) &&
        t_10_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_10 = 1;
        t_10_remove_marks( &avail_marking );
        t_10_add_marks( &add_marking );
        t_10_generate_output_events( &output_events );
    }

    /* Transition B2_copy */
    if( t_11_enabled( prev_marking, &avail_marking ) &&
        t_11_events( &input_events ) &&
        t_11_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_11 = 1;
        t_11_remove_marks( &avail_marking );
        t_11_add_marks( &add_marking );
        t_11_generate_output_events( &output_events );
    }

    /* Transition A2_copy */
    if( t_13_enabled( prev_marking, &avail_marking ) &&
        t_13_events( &input_events ) &&
        t_13_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_13 = 1;
        t_13_remove_marks( &avail_marking );
        t_13_add_marks( &add_marking );
        t_13_generate_output_events( &output_events );
    }

    /* Transition A3_copy */
    if( t_15_enabled( prev_marking, &avail_marking ) &&
        t_15_events( &input_events ) &&
        t_15_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_15 = 1;
        t_15_remove_marks( &avail_marking );
        t_15_add_marks( &add_marking );
        t_15_generate_output_events( &output_events );
    }

    /* Transition B3_copy */
    if( t_17_enabled( prev_marking, &avail_marking ) &&
        t_17_events( &input_events ) &&
        t_17_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_17 = 1;
        t_17_remove_marks( &avail_marking );
        t_17_add_marks( &add_marking );
        t_17_generate_output_events( &output_events );
    }

    /* Transition A4_copy */
    if( t_79_enabled( prev_marking, &avail_marking ) &&
        t_79_events( &input_events ) &&
        t_79_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_79 = 1;
        t_79_remove_marks( &avail_marking );
        t_79_add_marks( &add_marking );
        t_79_generate_output_events( &output_events );
    }

    /* Transition A6_copy */
    if( t_81_enabled( prev_marking, &avail_marking ) &&
        t_81_events( &input_events ) &&
        t_81_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_81 = 1;
        t_81_remove_marks( &avail_marking );
        t_81_add_marks( &add_marking );
        t_81_generate_output_events( &output_events );
    }

    /* Transition A8_copy */
    if( t_83_enabled( prev_marking, &avail_marking ) &&
        t_83_events( &input_events ) &&
        t_83_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_83 = 1;
        t_83_remove_marks( &avail_marking );
        t_83_add_marks( &add_marking );
        t_83_generate_output_events( &output_events );
    }

    /* Transition B4_copy */
    if( t_85_enabled( prev_marking, &avail_marking ) &&
        t_85_events( &input_events ) &&
        t_85_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_85 = 1;
        t_85_remove_marks( &avail_marking );
        t_85_add_marks( &add_marking );
        t_85_generate_output_events( &output_events );
    }

    /* Transition B6_copy */
    if( t_87_enabled( prev_marking, &avail_marking ) &&
        t_87_events( &input_events ) &&
        t_87_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_87 = 1;
        t_87_remove_marks( &avail_marking );
        t_87_add_marks( &add_marking );
        t_87_generate_output_events( &output_events );
    }

    /* Transition B8_copy */
    if( t_89_enabled( prev_marking, &avail_marking ) &&
        t_89_events( &input_events ) &&
        t_89_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_89 = 1;
        t_89_remove_marks( &avail_marking );
        t_89_add_marks( &add_marking );
        t_89_generate_output_events( &output_events );
    }

    /* Transition A5_copy */
    if( t_127_enabled( prev_marking, &avail_marking ) &&
        t_127_events( &input_events ) &&
        t_127_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_127 = 1;
        t_127_remove_marks( &avail_marking );
        t_127_add_marks( &add_marking );
        t_127_generate_output_events( &output_events );
    }

    /* Transition A7_copy */
    if( t_129_enabled( prev_marking, &avail_marking ) &&
        t_129_events( &input_events ) &&
        t_129_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_129 = 1;
        t_129_remove_marks( &avail_marking );
        t_129_add_marks( &add_marking );
        t_129_generate_output_events( &output_events );
    }

    /* Transition A9_copy */
    if( t_131_enabled( prev_marking, &avail_marking ) &&
        t_131_events( &input_events ) &&
        t_131_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_131 = 1;
        t_131_remove_marks( &avail_marking );
        t_131_add_marks( &add_marking );
        t_131_generate_output_events( &output_events );
    }

    /* Transition B5_copy */
    if( t_133_enabled( prev_marking, &avail_marking ) &&
        t_133_events( &input_events ) &&
        t_133_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_133 = 1;
        t_133_remove_marks( &avail_marking );
        t_133_add_marks( &add_marking );
        t_133_generate_output_events( &output_events );
    }

    /* Transition B7_copy */
    if( t_135_enabled( prev_marking, &avail_marking ) &&
        t_135_events( &input_events ) &&
        t_135_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_135 = 1;
        t_135_remove_marks( &avail_marking );
        t_135_add_marks( &add_marking );
        t_135_generate_output_events( &output_events );
    }

    /* Transition B9_copy */
    if( t_137_enabled( prev_marking, &avail_marking ) &&
        t_137_events( &input_events ) &&
        t_137_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_137 = 1;
        t_137_remove_marks( &avail_marking );
        t_137_add_marks( &add_marking );
        t_137_generate_output_events( &output_events );
    }

    add_N_3carros_TD_NetMarkings( &avail_marking, &add_marking );

    N_3carros_TD_GenerateTransitionActionOutputSignals( &tfired, &avail_marking, ev_out );
    N_3carros_TD_GeneratePlaceOutputSignals( &avail_marking, inputs, place_out, ev_out );
    N_3carros_TD_GenerateEventOutputSignals( &output_events, ev_out );
    N_3carros_TD_PutOutputSignals( place_out, ev_out, &output_events );
    *prev_marking = avail_marking;
}

N_3carros_TD_TransitionFiring* get_N_3carros_TD_TransitionFiring()
{
    return &tfired;
}

