/* Net N_3carros_TD - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include "net_types.h"


#define ABS(x) (((x)>=0)?(x):-(x))


/* Array implementation: */


void createInitial_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* init_marking )
{
    memset( init_marking, 0, sizeof(*init_marking) );
    init_marking->p_2 = 0; /* Place Car1_Move_Back */
    init_marking->p_3 = 1; /* Place Car1_Ready */
    init_marking->p_4 = 0; /* Place Car1_Arrived */
    init_marking->p_5 = 0; /* Place Car2_Arrived_copy */
    init_marking->p_6 = 0; /* Place Car1_Move_Forward */
    init_marking->p_12 = 1; /* Place Car2_Ready_copy */
    init_marking->p_14 = 1; /* Place Car3_Ready_copy */
    init_marking->p_16 = 0; /* Place Car3_Arrived_copy */
    init_marking->p_78 = 1; /* Place Car4_Ready_copy */
    init_marking->p_80 = 1; /* Place Car6_Ready_copy */
    init_marking->p_82 = 1; /* Place Car8_Ready_copy */
    init_marking->p_84 = 0; /* Place Car4_Arrived_copy */
    init_marking->p_86 = 0; /* Place Car6_Arrived_copy */
    init_marking->p_88 = 0; /* Place Car8_Arrived_copy */
    init_marking->p_126 = 1; /* Place Car5_Ready_copy */
    init_marking->p_128 = 1; /* Place Car7_Ready_copy */
    init_marking->p_130 = 1; /* Place Car9_Ready_copy */
    init_marking->p_132 = 0; /* Place Car5_Arrived_copy */
    init_marking->p_134 = 0; /* Place Car7_Arrived_copy */
    init_marking->p_136 = 0; /* Place Car9_Arrived_copy */
}

void createEmpty_N_3carros_TD_NetMarking( N_3carros_TD_NetMarking* empty_marking )
{
    empty_marking->p_2 = 0; /* Place Car1_Move_Back */
    empty_marking->p_3 = 0; /* Place Car1_Ready */
    empty_marking->p_4 = 0; /* Place Car1_Arrived */
    empty_marking->p_5 = 0; /* Place Car2_Arrived_copy */
    empty_marking->p_6 = 0; /* Place Car1_Move_Forward */
    empty_marking->p_12 = 0; /* Place Car2_Ready_copy */
    empty_marking->p_14 = 0; /* Place Car3_Ready_copy */
    empty_marking->p_16 = 0; /* Place Car3_Arrived_copy */
    empty_marking->p_78 = 0; /* Place Car4_Ready_copy */
    empty_marking->p_80 = 0; /* Place Car6_Ready_copy */
    empty_marking->p_82 = 0; /* Place Car8_Ready_copy */
    empty_marking->p_84 = 0; /* Place Car4_Arrived_copy */
    empty_marking->p_86 = 0; /* Place Car6_Arrived_copy */
    empty_marking->p_88 = 0; /* Place Car8_Arrived_copy */
    empty_marking->p_126 = 0; /* Place Car5_Ready_copy */
    empty_marking->p_128 = 0; /* Place Car7_Ready_copy */
    empty_marking->p_130 = 0; /* Place Car9_Ready_copy */
    empty_marking->p_132 = 0; /* Place Car5_Arrived_copy */
    empty_marking->p_134 = 0; /* Place Car7_Arrived_copy */
    empty_marking->p_136 = 0; /* Place Car9_Arrived_copy */
}

void add_N_3carros_TD_NetMarkings(
    N_3carros_TD_NetMarking* dest_marking,
    N_3carros_TD_NetMarking* source_marking )
{
    dest_marking->p_2 += source_marking->p_2; /* Place Car1_Move_Back */
    dest_marking->p_3 += source_marking->p_3; /* Place Car1_Ready */
    dest_marking->p_4 += source_marking->p_4; /* Place Car1_Arrived */
    dest_marking->p_5 += source_marking->p_5; /* Place Car2_Arrived_copy */
    dest_marking->p_6 += source_marking->p_6; /* Place Car1_Move_Forward */
    dest_marking->p_12 += source_marking->p_12; /* Place Car2_Ready_copy */
    dest_marking->p_14 += source_marking->p_14; /* Place Car3_Ready_copy */
    dest_marking->p_16 += source_marking->p_16; /* Place Car3_Arrived_copy */
    dest_marking->p_78 += source_marking->p_78; /* Place Car4_Ready_copy */
    dest_marking->p_80 += source_marking->p_80; /* Place Car6_Ready_copy */
    dest_marking->p_82 += source_marking->p_82; /* Place Car8_Ready_copy */
    dest_marking->p_84 += source_marking->p_84; /* Place Car4_Arrived_copy */
    dest_marking->p_86 += source_marking->p_86; /* Place Car6_Arrived_copy */
    dest_marking->p_88 += source_marking->p_88; /* Place Car8_Arrived_copy */
    dest_marking->p_126 += source_marking->p_126; /* Place Car5_Ready_copy */
    dest_marking->p_128 += source_marking->p_128; /* Place Car7_Ready_copy */
    dest_marking->p_130 += source_marking->p_130; /* Place Car9_Ready_copy */
    dest_marking->p_132 += source_marking->p_132; /* Place Car5_Arrived_copy */
    dest_marking->p_134 += source_marking->p_134; /* Place Car7_Arrived_copy */
    dest_marking->p_136 += source_marking->p_136; /* Place Car9_Arrived_copy */
}

void init_N_3carros_TD_OutputSignals(
    N_3carros_TD_PlaceOutputSignals* place_out,
    N_3carros_TD_EventOutputSignals* ev_out )
{
    memset( place_out, 0, sizeof(*place_out) );
    memset( ev_out, 0, sizeof(*ev_out) );
    place_out->car1_ready = 0;
    place_out->car1_arrived = 0;
    place_out->car5_ready = 0;
    place_out->car5_arrived = 0;
    place_out->car6_ready = 0;
    place_out->car6_arrived = 0;
}

/* Transition 7 - A1 */
int t_7_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_2 >= 1 );
}

int t_7_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_7_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_7_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_2--;
}

void t_7_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_3++;
}

void t_7_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 8 - GO */
int t_8_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_3 >= 1 && avail->p_12 >= 1 && avail->p_14 >= 1 && avail->p_82 >= 1 && avail->p_80 >= 1 && avail->p_78 >= 1 && avail->p_130 >= 1 && avail->p_128 >= 1 && avail->p_126 >= 1 );
}

int t_8_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_8_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_8_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_3--;
    marking->p_12--;
    marking->p_14--;
    marking->p_82--;
    marking->p_80--;
    marking->p_78--;
    marking->p_130--;
    marking->p_128--;
    marking->p_126--;
}

void t_8_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_6++;
}

void t_8_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
    ev_out->event71 = 1;
    ev_out->event115 = 1;
}


/* Transition 9 - BACK */
int t_9_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_5 >= 1 && avail->p_4 >= 1 && avail->p_16 >= 1 && avail->p_84 >= 1 && avail->p_86 >= 1 && avail->p_88 >= 1 && avail->p_132 >= 1 && avail->p_134 >= 1 && avail->p_136 >= 1 );
}

int t_9_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_9_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_9_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_5--;
    marking->p_4--;
    marking->p_16--;
    marking->p_84--;
    marking->p_86--;
    marking->p_88--;
    marking->p_132--;
    marking->p_134--;
    marking->p_136--;
}

void t_9_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_2++;
}

void t_9_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
    ev_out->event73 = 1;
    ev_out->event114 = 1;
}


/* Transition 10 - B1 */
int t_10_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( avail->p_6 >= 1 );
}

int t_10_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_10_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_10_remove_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_6--;
}

void t_10_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_4++;
}

void t_10_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 11 - B2_copy */
int t_11_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_11_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_11_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_11_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_11_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_5++;
}

void t_11_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 13 - A2_copy */
int t_13_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_13_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_13_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_13_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_13_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_12++;
}

void t_13_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 15 - A3_copy */
int t_15_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_15_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_15_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_15_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_15_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_14++;
}

void t_15_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 17 - B3_copy */
int t_17_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_17_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_17_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_17_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_17_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_16++;
}

void t_17_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 79 - A4_copy */
int t_79_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_79_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_79_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_79_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_79_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_78++;
}

void t_79_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 81 - A6_copy */
int t_81_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_81_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event70 );
}

int t_81_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_81_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_81_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_80++;
}

void t_81_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 83 - A8_copy */
int t_83_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_83_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_83_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_83_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_83_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_82++;
}

void t_83_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 85 - B4_copy */
int t_85_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_85_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_85_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_85_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_85_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_84++;
}

void t_85_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 87 - B6_copy */
int t_87_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_87_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event72 );
}

int t_87_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_87_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_87_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_86++;
}

void t_87_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 89 - B8_copy */
int t_89_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_89_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_89_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_89_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_89_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_88++;
}

void t_89_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 127 - A5_copy */
int t_127_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_127_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event117 );
}

int t_127_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_127_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_127_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_126++;
}

void t_127_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 129 - A7_copy */
int t_129_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_129_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_129_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_129_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_129_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_128++;
}

void t_129_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 131 - A9_copy */
int t_131_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_131_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_131_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_131_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_131_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_130++;
}

void t_131_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 133 - B5_copy */
int t_133_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_133_events( N_3carros_TD_InputSignalEvents* events )
{
    return ( events->event116 );
}

int t_133_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_133_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_133_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_132++;
}

void t_133_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 135 - B7_copy */
int t_135_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_135_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_135_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_135_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_135_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_134++;
}

void t_135_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Transition 137 - B9_copy */
int t_137_enabled( N_3carros_TD_NetMarking* prev,
                    N_3carros_TD_NetMarking* avail )
{
    return ( 1 );
}

int t_137_events( N_3carros_TD_InputSignalEvents* events )
{
    return (  1  );
}

int t_137_guards( N_3carros_TD_NetMarking* marking,
                   N_3carros_TD_InputSignals* inputs,
                   N_3carros_TD_PlaceOutputSignals* place_out,
                   N_3carros_TD_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_137_remove_marks( N_3carros_TD_NetMarking* marking )
{
}

void t_137_add_marks( N_3carros_TD_NetMarking* marking )
{
    marking->p_136++;
}

void t_137_generate_output_events( N_3carros_TD_OutputSignalEvents* ev_out )
{
}


/* Input event processing: */
void N_3carros_TD_GenerateInputSignalEvents(
        N_3carros_TD_InputSignals *old_values,
        N_3carros_TD_InputSignals *new_values,
        N_3carros_TD_InputSignalEvents *events )
{
}

/* Output event processing: */
void N_3carros_TD_GenerateEventOutputSignals(
    N_3carros_TD_OutputSignalEvents *events,
    N_3carros_TD_EventOutputSignals *signals )
{
}

/* Transition action processing: */
void N_3carros_TD_GenerateTransitionActionOutputSignals(
    N_3carros_TD_TransitionFiring *tfired,
    N_3carros_TD_NetMarking *marking,
    N_3carros_TD_EventOutputSignals *ev_out )
{
}

/* Place Output Processing */
void N_3carros_TD_GeneratePlaceOutputSignals(
    N_3carros_TD_NetMarking *marking,
    N_3carros_TD_InputSignals *inputs,
    N_3carros_TD_PlaceOutputSignals *place_out,
    N_3carros_TD_EventOutputSignals *ev_out )
{
    int exp_res, new_val, n_writes;
    N_3carros_TD_PlaceOutputSignals new_out = *place_out;
    
    /* Signal car1_ready */
    new_val = 0;
    if( marking->p_3 > 0 ) { /* Place Car1_Ready */
        exp_res = marking->p_3 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.car1_ready = 1;
    else if( new_val < 0 ) new_out.car1_ready = 0;
    else new_out.car1_ready = new_val;

    /* Signal car1_arrived */
    new_val = 0;
    if( marking->p_4 > 0 ) { /* Place Car1_Arrived */
        exp_res = marking->p_4 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.car1_arrived = 1;
    else if( new_val < 0 ) new_out.car1_arrived = 0;
    else new_out.car1_arrived = new_val;

    /* Signal car5_ready */
    new_val = 0;
    if( marking->p_126 > 0 ) { /* Place Car5_Ready_copy */
        exp_res = marking->p_126 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.car5_ready = 1;
    else if( new_val < 0 ) new_out.car5_ready = 0;
    else new_out.car5_ready = new_val;

    /* Signal car5_arrived */
    new_val = 0;
    if( marking->p_132 > 0 ) { /* Place Car5_Arrived_copy */
        exp_res = marking->p_132 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.car5_arrived = 1;
    else if( new_val < 0 ) new_out.car5_arrived = 0;
    else new_out.car5_arrived = new_val;

    /* Signal car6_ready */
    new_val = 0;
    if( marking->p_80 > 0 ) { /* Place Car6_Ready_copy */
        exp_res = marking->p_80 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.car6_ready = 1;
    else if( new_val < 0 ) new_out.car6_ready = 0;
    else new_out.car6_ready = new_val;

    /* Signal car6_arrived */
    new_val = 0;
    if( marking->p_86 > 0 ) { /* Place Car6_Arrived_copy */
        exp_res = marking->p_86 == 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.car6_arrived = 1;
    else if( new_val < 0 ) new_out.car6_arrived = 0;
    else new_out.car6_arrived = new_val;

    *place_out = new_out;
}

